##
## Copyright (C) by Argonne National Laboratory
##     See COPYRIGHT in top-level directory
##

# -- THIS FILE IS AUTO-GENERATED -- 

mpi_sources += \
    src/binding/c/c_binding.c
doc3_src_txt += \
    src/binding/c/mansrc/attr_delete.txt \
    src/binding/c/mansrc/attr_get.txt \
    src/binding/c/mansrc/attr_put.txt \
    src/binding/c/mansrc/comm_create_keyval.txt \
    src/binding/c/mansrc/comm_delete_attr.txt \
    src/binding/c/mansrc/comm_free_keyval.txt \
    src/binding/c/mansrc/comm_get_attr.txt \
    src/binding/c/mansrc/comm_set_attr.txt \
    src/binding/c/mansrc/keyval_create.txt \
    src/binding/c/mansrc/keyval_free.txt \
    src/binding/c/mansrc/type_create_keyval.txt \
    src/binding/c/mansrc/type_delete_attr.txt \
    src/binding/c/mansrc/type_free_keyval.txt \
    src/binding/c/mansrc/type_get_attr.txt \
    src/binding/c/mansrc/type_set_attr.txt \
    src/binding/c/mansrc/win_create_keyval.txt \
    src/binding/c/mansrc/win_delete_attr.txt \
    src/binding/c/mansrc/win_free_keyval.txt \
    src/binding/c/mansrc/win_get_attr.txt \
    src/binding/c/mansrc/win_set_attr.txt \
    src/binding/c/mansrc/allgather.txt \
    src/binding/c/mansrc/allgather_init.txt \
    src/binding/c/mansrc/allgatherv.txt \
    src/binding/c/mansrc/allgatherv_init.txt \
    src/binding/c/mansrc/allreduce.txt \
    src/binding/c/mansrc/allreduce_init.txt \
    src/binding/c/mansrc/alltoall.txt \
    src/binding/c/mansrc/alltoall_init.txt \
    src/binding/c/mansrc/alltoallv.txt \
    src/binding/c/mansrc/alltoallv_init.txt \
    src/binding/c/mansrc/alltoallw.txt \
    src/binding/c/mansrc/alltoallw_init.txt \
    src/binding/c/mansrc/barrier.txt \
    src/binding/c/mansrc/barrier_init.txt \
    src/binding/c/mansrc/bcast.txt \
    src/binding/c/mansrc/bcast_init.txt \
    src/binding/c/mansrc/exscan.txt \
    src/binding/c/mansrc/exscan_init.txt \
    src/binding/c/mansrc/gather.txt \
    src/binding/c/mansrc/gather_init.txt \
    src/binding/c/mansrc/gatherv.txt \
    src/binding/c/mansrc/gatherv_init.txt \
    src/binding/c/mansrc/iallgather.txt \
    src/binding/c/mansrc/iallgatherv.txt \
    src/binding/c/mansrc/iallreduce.txt \
    src/binding/c/mansrc/ialltoall.txt \
    src/binding/c/mansrc/ialltoallv.txt \
    src/binding/c/mansrc/ialltoallw.txt \
    src/binding/c/mansrc/ibarrier.txt \
    src/binding/c/mansrc/ibcast.txt \
    src/binding/c/mansrc/iexscan.txt \
    src/binding/c/mansrc/igather.txt \
    src/binding/c/mansrc/igatherv.txt \
    src/binding/c/mansrc/ineighbor_allgather.txt \
    src/binding/c/mansrc/ineighbor_allgatherv.txt \
    src/binding/c/mansrc/ineighbor_alltoall.txt \
    src/binding/c/mansrc/ineighbor_alltoallv.txt \
    src/binding/c/mansrc/ineighbor_alltoallw.txt \
    src/binding/c/mansrc/ireduce.txt \
    src/binding/c/mansrc/ireduce_scatter.txt \
    src/binding/c/mansrc/ireduce_scatter_block.txt \
    src/binding/c/mansrc/iscan.txt \
    src/binding/c/mansrc/iscatter.txt \
    src/binding/c/mansrc/iscatterv.txt \
    src/binding/c/mansrc/neighbor_allgather.txt \
    src/binding/c/mansrc/neighbor_allgather_init.txt \
    src/binding/c/mansrc/neighbor_allgatherv.txt \
    src/binding/c/mansrc/neighbor_allgatherv_init.txt \
    src/binding/c/mansrc/neighbor_alltoall.txt \
    src/binding/c/mansrc/neighbor_alltoall_init.txt \
    src/binding/c/mansrc/neighbor_alltoallv.txt \
    src/binding/c/mansrc/neighbor_alltoallv_init.txt \
    src/binding/c/mansrc/neighbor_alltoallw.txt \
    src/binding/c/mansrc/neighbor_alltoallw_init.txt \
    src/binding/c/mansrc/reduce.txt \
    src/binding/c/mansrc/reduce_init.txt \
    src/binding/c/mansrc/reduce_local.txt \
    src/binding/c/mansrc/reduce_scatter.txt \
    src/binding/c/mansrc/reduce_scatter_block.txt \
    src/binding/c/mansrc/reduce_scatter_block_init.txt \
    src/binding/c/mansrc/reduce_scatter_init.txt \
    src/binding/c/mansrc/scan.txt \
    src/binding/c/mansrc/scan_init.txt \
    src/binding/c/mansrc/scatter.txt \
    src/binding/c/mansrc/scatter_init.txt \
    src/binding/c/mansrc/scatterv.txt \
    src/binding/c/mansrc/scatterv_init.txt \
    src/binding/c/mansrc/comm_compare.txt \
    src/binding/c/mansrc/comm_create.txt \
    src/binding/c/mansrc/comm_create_group.txt \
    src/binding/c/mansrc/comm_dup.txt \
    src/binding/c/mansrc/comm_dup_with_info.txt \
    src/binding/c/mansrc/comm_free.txt \
    src/binding/c/mansrc/comm_get_info.txt \
    src/binding/c/mansrc/comm_get_name.txt \
    src/binding/c/mansrc/comm_group.txt \
    src/binding/c/mansrc/comm_idup.txt \
    src/binding/c/mansrc/comm_idup_with_info.txt \
    src/binding/c/mansrc/comm_rank.txt \
    src/binding/c/mansrc/comm_remote_group.txt \
    src/binding/c/mansrc/comm_remote_size.txt \
    src/binding/c/mansrc/comm_set_info.txt \
    src/binding/c/mansrc/comm_set_name.txt \
    src/binding/c/mansrc/comm_size.txt \
    src/binding/c/mansrc/comm_split.txt \
    src/binding/c/mansrc/comm_split_type.txt \
    src/binding/c/mansrc/comm_test_inter.txt \
    src/binding/c/mansrc/intercomm_create.txt \
    src/binding/c/mansrc/intercomm_create_from_groups.txt \
    src/binding/c/mansrc/intercomm_merge.txt \
    src/binding/c/mansrc/comm_test_threadcomm.txt \
    src/binding/c/mansrc/comm_revoke.txt \
    src/binding/c/mansrc/comm_shrink.txt \
    src/binding/c/mansrc/comm_failure_ack.txt \
    src/binding/c/mansrc/comm_failure_get_acked.txt \
    src/binding/c/mansrc/comm_agree.txt \
    src/binding/c/mansrc/comm_get_failed.txt \
    src/binding/c/mansrc/get_address.txt \
    src/binding/c/mansrc/get_count.txt \
    src/binding/c/mansrc/get_elements.txt \
    src/binding/c/mansrc/get_elements_x.txt \
    src/binding/c/mansrc/pack.txt \
    src/binding/c/mansrc/pack_external.txt \
    src/binding/c/mansrc/pack_external_size.txt \
    src/binding/c/mansrc/pack_size.txt \
    src/binding/c/mansrc/status_set_elements.txt \
    src/binding/c/mansrc/status_set_elements_x.txt \
    src/binding/c/mansrc/type_commit.txt \
    src/binding/c/mansrc/type_contiguous.txt \
    src/binding/c/mansrc/type_create_darray.txt \
    src/binding/c/mansrc/type_create_hindexed.txt \
    src/binding/c/mansrc/type_create_hindexed_block.txt \
    src/binding/c/mansrc/type_create_hvector.txt \
    src/binding/c/mansrc/type_create_indexed_block.txt \
    src/binding/c/mansrc/type_create_resized.txt \
    src/binding/c/mansrc/type_create_struct.txt \
    src/binding/c/mansrc/type_create_subarray.txt \
    src/binding/c/mansrc/type_dup.txt \
    src/binding/c/mansrc/type_free.txt \
    src/binding/c/mansrc/type_get_contents.txt \
    src/binding/c/mansrc/type_get_envelope.txt \
    src/binding/c/mansrc/type_get_extent.txt \
    src/binding/c/mansrc/type_get_extent_x.txt \
    src/binding/c/mansrc/type_get_name.txt \
    src/binding/c/mansrc/type_get_true_extent.txt \
    src/binding/c/mansrc/type_get_true_extent_x.txt \
    src/binding/c/mansrc/type_get_value_index.txt \
    src/binding/c/mansrc/type_indexed.txt \
    src/binding/c/mansrc/type_match_size.txt \
    src/binding/c/mansrc/type_set_name.txt \
    src/binding/c/mansrc/type_size.txt \
    src/binding/c/mansrc/type_size_x.txt \
    src/binding/c/mansrc/type_vector.txt \
    src/binding/c/mansrc/unpack.txt \
    src/binding/c/mansrc/unpack_external.txt \
    src/binding/c/mansrc/address.txt \
    src/binding/c/mansrc/type_extent.txt \
    src/binding/c/mansrc/type_lb.txt \
    src/binding/c/mansrc/type_ub.txt \
    src/binding/c/mansrc/type_hindexed.txt \
    src/binding/c/mansrc/type_hvector.txt \
    src/binding/c/mansrc/type_struct.txt \
    src/binding/c/mansrc/type_iov_len.txt \
    src/binding/c/mansrc/type_iov.txt \
    src/binding/c/mansrc/add_error_class.txt \
    src/binding/c/mansrc/add_error_code.txt \
    src/binding/c/mansrc/add_error_string.txt \
    src/binding/c/mansrc/comm_call_errhandler.txt \
    src/binding/c/mansrc/comm_create_errhandler.txt \
    src/binding/c/mansrc/comm_get_errhandler.txt \
    src/binding/c/mansrc/comm_set_errhandler.txt \
    src/binding/c/mansrc/errhandler_free.txt \
    src/binding/c/mansrc/error_class.txt \
    src/binding/c/mansrc/error_string.txt \
    src/binding/c/mansrc/file_call_errhandler.txt \
    src/binding/c/mansrc/file_create_errhandler.txt \
    src/binding/c/mansrc/file_get_errhandler.txt \
    src/binding/c/mansrc/file_set_errhandler.txt \
    src/binding/c/mansrc/remove_error_class.txt \
    src/binding/c/mansrc/remove_error_code.txt \
    src/binding/c/mansrc/remove_error_string.txt \
    src/binding/c/mansrc/session_call_errhandler.txt \
    src/binding/c/mansrc/session_create_errhandler.txt \
    src/binding/c/mansrc/session_get_errhandler.txt \
    src/binding/c/mansrc/session_set_errhandler.txt \
    src/binding/c/mansrc/win_call_errhandler.txt \
    src/binding/c/mansrc/win_create_errhandler.txt \
    src/binding/c/mansrc/win_get_errhandler.txt \
    src/binding/c/mansrc/win_set_errhandler.txt \
    src/binding/c/mansrc/errhandler_create.txt \
    src/binding/c/mansrc/errhandler_get.txt \
    src/binding/c/mansrc/errhandler_set.txt \
    src/binding/c/mansrc/comm_c2f.txt \
    src/binding/c/mansrc/comm_f2c.txt \
    src/binding/c/mansrc/errhandler_c2f.txt \
    src/binding/c/mansrc/errhandler_f2c.txt \
    src/binding/c/mansrc/group_c2f.txt \
    src/binding/c/mansrc/group_f2c.txt \
    src/binding/c/mansrc/info_c2f.txt \
    src/binding/c/mansrc/info_f2c.txt \
    src/binding/c/mansrc/message_c2f.txt \
    src/binding/c/mansrc/message_f2c.txt \
    src/binding/c/mansrc/op_c2f.txt \
    src/binding/c/mansrc/op_f2c.txt \
    src/binding/c/mansrc/request_c2f.txt \
    src/binding/c/mansrc/request_f2c.txt \
    src/binding/c/mansrc/session_c2f.txt \
    src/binding/c/mansrc/session_f2c.txt \
    src/binding/c/mansrc/type_c2f.txt \
    src/binding/c/mansrc/type_f2c.txt \
    src/binding/c/mansrc/win_c2f.txt \
    src/binding/c/mansrc/win_f2c.txt \
    src/binding/c/mansrc/group_compare.txt \
    src/binding/c/mansrc/group_difference.txt \
    src/binding/c/mansrc/group_excl.txt \
    src/binding/c/mansrc/group_free.txt \
    src/binding/c/mansrc/group_incl.txt \
    src/binding/c/mansrc/group_intersection.txt \
    src/binding/c/mansrc/group_range_excl.txt \
    src/binding/c/mansrc/group_range_incl.txt \
    src/binding/c/mansrc/group_rank.txt \
    src/binding/c/mansrc/group_size.txt \
    src/binding/c/mansrc/group_translate_ranks.txt \
    src/binding/c/mansrc/group_union.txt \
    src/binding/c/mansrc/info_create.txt \
    src/binding/c/mansrc/info_create_env.txt \
    src/binding/c/mansrc/info_delete.txt \
    src/binding/c/mansrc/info_dup.txt \
    src/binding/c/mansrc/info_free.txt \
    src/binding/c/mansrc/info_get.txt \
    src/binding/c/mansrc/info_get_nkeys.txt \
    src/binding/c/mansrc/info_get_nthkey.txt \
    src/binding/c/mansrc/info_get_string.txt \
    src/binding/c/mansrc/info_get_valuelen.txt \
    src/binding/c/mansrc/info_set.txt \
    src/binding/c/mansrc/info_set_hex.txt \
    src/binding/c/mansrc/abort.txt \
    src/binding/c/mansrc/comm_create_from_group.txt \
    src/binding/c/mansrc/finalize.txt \
    src/binding/c/mansrc/finalized.txt \
    src/binding/c/mansrc/group_from_session_pset.txt \
    src/binding/c/mansrc/init.txt \
    src/binding/c/mansrc/init_thread.txt \
    src/binding/c/mansrc/initialized.txt \
    src/binding/c/mansrc/is_thread_main.txt \
    src/binding/c/mansrc/query_thread.txt \
    src/binding/c/mansrc/session_finalize.txt \
    src/binding/c/mansrc/session_get_info.txt \
    src/binding/c/mansrc/session_get_nth_pset.txt \
    src/binding/c/mansrc/session_get_num_psets.txt \
    src/binding/c/mansrc/session_get_pset_info.txt \
    src/binding/c/mansrc/session_init.txt \
    src/binding/c/mansrc/aint_add.txt \
    src/binding/c/mansrc/aint_diff.txt \
    src/binding/c/mansrc/get_library_version.txt \
    src/binding/c/mansrc/get_processor_name.txt \
    src/binding/c/mansrc/get_version.txt \
    src/binding/c/mansrc/pcontrol.txt \
    src/binding/c/mansrc/gpu_query_support.txt \
    src/binding/c/mansrc/query_cuda_support.txt \
    src/binding/c/mansrc/query_ze_support.txt \
    src/binding/c/mansrc/query_hip_support.txt \
    src/binding/c/mansrc/category_changed.txt \
    src/binding/c/mansrc/category_get_categories.txt \
    src/binding/c/mansrc/category_get_cvars.txt \
    src/binding/c/mansrc/category_get_events.txt \
    src/binding/c/mansrc/category_get_index.txt \
    src/binding/c/mansrc/category_get_info.txt \
    src/binding/c/mansrc/category_get_num.txt \
    src/binding/c/mansrc/category_get_num_events.txt \
    src/binding/c/mansrc/category_get_pvars.txt \
    src/binding/c/mansrc/cvar_get_index.txt \
    src/binding/c/mansrc/cvar_get_info.txt \
    src/binding/c/mansrc/cvar_get_num.txt \
    src/binding/c/mansrc/cvar_handle_alloc.txt \
    src/binding/c/mansrc/cvar_handle_free.txt \
    src/binding/c/mansrc/cvar_read.txt \
    src/binding/c/mansrc/cvar_write.txt \
    src/binding/c/mansrc/enum_get_info.txt \
    src/binding/c/mansrc/enum_get_item.txt \
    src/binding/c/mansrc/event_callback_get_info.txt \
    src/binding/c/mansrc/event_callback_set_info.txt \
    src/binding/c/mansrc/event_copy.txt \
    src/binding/c/mansrc/event_get_index.txt \
    src/binding/c/mansrc/event_get_info.txt \
    src/binding/c/mansrc/event_get_num.txt \
    src/binding/c/mansrc/event_get_source.txt \
    src/binding/c/mansrc/event_get_timestamp.txt \
    src/binding/c/mansrc/event_handle_alloc.txt \
    src/binding/c/mansrc/event_handle_free.txt \
    src/binding/c/mansrc/event_handle_get_info.txt \
    src/binding/c/mansrc/event_handle_set_info.txt \
    src/binding/c/mansrc/event_read.txt \
    src/binding/c/mansrc/event_register_callback.txt \
    src/binding/c/mansrc/event_set_dropped_handler.txt \
    src/binding/c/mansrc/finalize.txt \
    src/binding/c/mansrc/init_thread.txt \
    src/binding/c/mansrc/pvar_get_index.txt \
    src/binding/c/mansrc/pvar_get_info.txt \
    src/binding/c/mansrc/pvar_get_num.txt \
    src/binding/c/mansrc/pvar_handle_alloc.txt \
    src/binding/c/mansrc/pvar_handle_free.txt \
    src/binding/c/mansrc/pvar_read.txt \
    src/binding/c/mansrc/pvar_readreset.txt \
    src/binding/c/mansrc/pvar_reset.txt \
    src/binding/c/mansrc/pvar_session_create.txt \
    src/binding/c/mansrc/pvar_session_free.txt \
    src/binding/c/mansrc/pvar_start.txt \
    src/binding/c/mansrc/pvar_stop.txt \
    src/binding/c/mansrc/pvar_write.txt \
    src/binding/c/mansrc/source_get_info.txt \
    src/binding/c/mansrc/source_get_num.txt \
    src/binding/c/mansrc/source_get_timestamp.txt \
    src/binding/c/mansrc/op_commutative.txt \
    src/binding/c/mansrc/op_create.txt \
    src/binding/c/mansrc/op_free.txt \
    src/binding/c/mansrc/parrived.txt \
    src/binding/c/mansrc/pready.txt \
    src/binding/c/mansrc/pready_list.txt \
    src/binding/c/mansrc/pready_range.txt \
    src/binding/c/mansrc/precv_init.txt \
    src/binding/c/mansrc/psend_init.txt \
    src/binding/c/mansrc/bsend.txt \
    src/binding/c/mansrc/bsend_init.txt \
    src/binding/c/mansrc/buffer_attach.txt \
    src/binding/c/mansrc/buffer_detach.txt \
    src/binding/c/mansrc/buffer_flush.txt \
    src/binding/c/mansrc/buffer_iflush.txt \
    src/binding/c/mansrc/comm_attach_buffer.txt \
    src/binding/c/mansrc/comm_detach_buffer.txt \
    src/binding/c/mansrc/comm_flush_buffer.txt \
    src/binding/c/mansrc/comm_iflush_buffer.txt \
    src/binding/c/mansrc/ibsend.txt \
    src/binding/c/mansrc/improbe.txt \
    src/binding/c/mansrc/imrecv.txt \
    src/binding/c/mansrc/iprobe.txt \
    src/binding/c/mansrc/irecv.txt \
    src/binding/c/mansrc/irsend.txt \
    src/binding/c/mansrc/isend.txt \
    src/binding/c/mansrc/isendrecv.txt \
    src/binding/c/mansrc/isendrecv_replace.txt \
    src/binding/c/mansrc/issend.txt \
    src/binding/c/mansrc/mprobe.txt \
    src/binding/c/mansrc/mrecv.txt \
    src/binding/c/mansrc/probe.txt \
    src/binding/c/mansrc/recv.txt \
    src/binding/c/mansrc/recv_init.txt \
    src/binding/c/mansrc/rsend.txt \
    src/binding/c/mansrc/rsend_init.txt \
    src/binding/c/mansrc/send.txt \
    src/binding/c/mansrc/send_init.txt \
    src/binding/c/mansrc/sendrecv.txt \
    src/binding/c/mansrc/sendrecv_replace.txt \
    src/binding/c/mansrc/session_attach_buffer.txt \
    src/binding/c/mansrc/session_detach_buffer.txt \
    src/binding/c/mansrc/session_flush_buffer.txt \
    src/binding/c/mansrc/session_iflush_buffer.txt \
    src/binding/c/mansrc/ssend.txt \
    src/binding/c/mansrc/ssend_init.txt \
    src/binding/c/mansrc/cancel.txt \
    src/binding/c/mansrc/grequest_complete.txt \
    src/binding/c/mansrc/grequest_start.txt \
    src/binding/c/mansrc/request_free.txt \
    src/binding/c/mansrc/request_get_status.txt \
    src/binding/c/mansrc/request_get_status_all.txt \
    src/binding/c/mansrc/request_get_status_any.txt \
    src/binding/c/mansrc/request_get_status_some.txt \
    src/binding/c/mansrc/start.txt \
    src/binding/c/mansrc/startall.txt \
    src/binding/c/mansrc/status_c2f.txt \
    src/binding/c/mansrc/status_f2c.txt \
    src/binding/c/mansrc/status_get_error.txt \
    src/binding/c/mansrc/status_get_source.txt \
    src/binding/c/mansrc/status_get_tag.txt \
    src/binding/c/mansrc/status_set_error.txt \
    src/binding/c/mansrc/status_set_source.txt \
    src/binding/c/mansrc/status_set_tag.txt \
    src/binding/c/mansrc/status_set_cancelled.txt \
    src/binding/c/mansrc/test.txt \
    src/binding/c/mansrc/test_cancelled.txt \
    src/binding/c/mansrc/testall.txt \
    src/binding/c/mansrc/testany.txt \
    src/binding/c/mansrc/testsome.txt \
    src/binding/c/mansrc/wait.txt \
    src/binding/c/mansrc/waitall.txt \
    src/binding/c/mansrc/waitany.txt \
    src/binding/c/mansrc/waitsome.txt \
    src/binding/c/mansrc/grequest_start_x.txt \
    src/binding/c/mansrc/grequest_class_create.txt \
    src/binding/c/mansrc/grequest_class_allocate.txt \
    src/binding/c/mansrc/accumulate.txt \
    src/binding/c/mansrc/alloc_mem.txt \
    src/binding/c/mansrc/compare_and_swap.txt \
    src/binding/c/mansrc/fetch_and_op.txt \
    src/binding/c/mansrc/free_mem.txt \
    src/binding/c/mansrc/get.txt \
    src/binding/c/mansrc/get_accumulate.txt \
    src/binding/c/mansrc/put.txt \
    src/binding/c/mansrc/raccumulate.txt \
    src/binding/c/mansrc/rget.txt \
    src/binding/c/mansrc/rget_accumulate.txt \
    src/binding/c/mansrc/rput.txt \
    src/binding/c/mansrc/win_allocate.txt \
    src/binding/c/mansrc/win_allocate_shared.txt \
    src/binding/c/mansrc/win_attach.txt \
    src/binding/c/mansrc/win_complete.txt \
    src/binding/c/mansrc/win_create.txt \
    src/binding/c/mansrc/win_create_dynamic.txt \
    src/binding/c/mansrc/win_detach.txt \
    src/binding/c/mansrc/win_fence.txt \
    src/binding/c/mansrc/win_flush.txt \
    src/binding/c/mansrc/win_flush_all.txt \
    src/binding/c/mansrc/win_flush_local.txt \
    src/binding/c/mansrc/win_flush_local_all.txt \
    src/binding/c/mansrc/win_free.txt \
    src/binding/c/mansrc/win_get_group.txt \
    src/binding/c/mansrc/win_get_info.txt \
    src/binding/c/mansrc/win_get_name.txt \
    src/binding/c/mansrc/win_lock.txt \
    src/binding/c/mansrc/win_lock_all.txt \
    src/binding/c/mansrc/win_post.txt \
    src/binding/c/mansrc/win_set_info.txt \
    src/binding/c/mansrc/win_set_name.txt \
    src/binding/c/mansrc/win_shared_query.txt \
    src/binding/c/mansrc/win_start.txt \
    src/binding/c/mansrc/win_sync.txt \
    src/binding/c/mansrc/win_test.txt \
    src/binding/c/mansrc/win_unlock.txt \
    src/binding/c/mansrc/win_unlock_all.txt \
    src/binding/c/mansrc/win_wait.txt \
    src/binding/c/mansrc/close_port.txt \
    src/binding/c/mansrc/comm_accept.txt \
    src/binding/c/mansrc/comm_connect.txt \
    src/binding/c/mansrc/comm_disconnect.txt \
    src/binding/c/mansrc/comm_get_parent.txt \
    src/binding/c/mansrc/comm_join.txt \
    src/binding/c/mansrc/comm_spawn.txt \
    src/binding/c/mansrc/comm_spawn_multiple.txt \
    src/binding/c/mansrc/lookup_name.txt \
    src/binding/c/mansrc/open_port.txt \
    src/binding/c/mansrc/publish_name.txt \
    src/binding/c/mansrc/unpublish_name.txt \
    src/binding/c/mansrc/stream_create.txt \
    src/binding/c/mansrc/stream_free.txt \
    src/binding/c/mansrc/stream_comm_create.txt \
    src/binding/c/mansrc/stream_comm_create_multiplex.txt \
    src/binding/c/mansrc/comm_get_stream.txt \
    src/binding/c/mansrc/stream_progress.txt \
    src/binding/c/mansrc/start_progress_thread.txt \
    src/binding/c/mansrc/stop_progress_thread.txt \
    src/binding/c/mansrc/stream_send.txt \
    src/binding/c/mansrc/stream_isend.txt \
    src/binding/c/mansrc/stream_recv.txt \
    src/binding/c/mansrc/stream_irecv.txt \
    src/binding/c/mansrc/send_enqueue.txt \
    src/binding/c/mansrc/recv_enqueue.txt \
    src/binding/c/mansrc/isend_enqueue.txt \
    src/binding/c/mansrc/irecv_enqueue.txt \
    src/binding/c/mansrc/wait_enqueue.txt \
    src/binding/c/mansrc/waitall_enqueue.txt \
    src/binding/c/mansrc/allreduce_enqueue.txt \
    src/binding/c/mansrc/threadcomm_init.txt \
    src/binding/c/mansrc/threadcomm_free.txt \
    src/binding/c/mansrc/threadcomm_start.txt \
    src/binding/c/mansrc/threadcomm_finish.txt \
    src/binding/c/mansrc/wtick.txt \
    src/binding/c/mansrc/wtime.txt \
    src/binding/c/mansrc/cart_coords.txt \
    src/binding/c/mansrc/cart_create.txt \
    src/binding/c/mansrc/cart_get.txt \
    src/binding/c/mansrc/cart_map.txt \
    src/binding/c/mansrc/cart_rank.txt \
    src/binding/c/mansrc/cart_shift.txt \
    src/binding/c/mansrc/cart_sub.txt \
    src/binding/c/mansrc/cartdim_get.txt \
    src/binding/c/mansrc/dims_create.txt \
    src/binding/c/mansrc/dist_graph_create.txt \
    src/binding/c/mansrc/dist_graph_create_adjacent.txt \
    src/binding/c/mansrc/dist_graph_neighbors.txt \
    src/binding/c/mansrc/dist_graph_neighbors_count.txt \
    src/binding/c/mansrc/get_hw_resource_info.txt \
    src/binding/c/mansrc/graph_create.txt \
    src/binding/c/mansrc/graph_get.txt \
    src/binding/c/mansrc/graph_map.txt \
    src/binding/c/mansrc/graph_neighbors.txt \
    src/binding/c/mansrc/graph_neighbors_count.txt \
    src/binding/c/mansrc/graphdims_get.txt \
    src/binding/c/mansrc/topo_test.txt
