.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Torquil Macdonald Sørensen <torquil@gmail.com>,
.\"
.TH mpivars 1 "2015-11-05"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
mpivars \- Print MPI variables
.SH SYNOPSIS
.B mpivars
.RI [ options ]
.SH DESCRIPTION
.PP
\fBmpivars\fP prints a detailed list of MPI-related variables to screen.
.SH OPTIONS
If no options are specified, variable descriptions are included in the output.
.TP
.B \-nodesc
Don't include variable descriptions.
.SH AUTHOR
This manpage was written by Torquil Macdonald S\[u00F8]rensen <torquil@gmail.com>.
.SH SEE ALSO
.BR mpiexec.hydra (1),
.BR mpicc.mpich (1),
.BR mpicxx.mpich (1),
.BR mpif77.mpich (1),
.BR mpif90.mpich (1),
.BR mpifort.mpich (1).
